---
 - name: install lamp stack
   hosts: all
   become: yes
   tasks: 
    - name: Install apache2 and update ubuntu packages
      apt:
        name: apche2
        update_cache: yes
        state: present
    - name: install libapache2-mod-php
      apt:
        name: php
        state: present
    - name: install php-mysql
      apt:
        name: php-cli
        state: present
    - name: copy info.php
      copy:
        src: info.php
        dest: /var/www/html/info.php
